name: Ci

on:
    push: 
        branches: [main]

jobs: 
    build:
        runs-on: self-hosted
        steps:
        - name: 'Build'
          run: |
                echo 'Build...'
                echo '10101010' >> build.bin
                

