on:
    push: 
        branches: [main]

jobs: 
    build:
        runs-on: self-hosted
        steps:
            - name: 'Build'
              run: |
                    echo "import sys
                    if __name__ == '__main__':
                        for param in sys.argv:
                            print(param)" > runer.py
            - name: 'Run'
              run: |
                python runer.py 1 2 3 4 > log.bin
    test:
        uses: DragoSaD-byte/Try_CI_2/.github/workflows/ci2_call.yml

