name: Ci

on:
    push: 
        branches: [main]

jobs: 
    build:
        runs-on: self-hosted
        steps:
            - name: 'Run'
              run: |
                    echo 'import sys \
if __name__ == "__main__": \
    for param in sys.argv:\
        print (param) ' >> test.py
                    python test.py

